tfidf:
  max_features: 50000
  ngram_range: [1, 2]

models:
  logistic_regression:
    init_params:
      max_iter: 1000
      random_state: 42
    param_grid:
      C: [0.01, 0.1, 1, 10]
  naive_bayes:
    init_params: {}
    param_grid:
      alpha: [0.01, 0.1, 1, 10]
  linear_svm:
    init_params:
      max_iter: 2000
      random_state: 42
    param_grid:
      C: [0.01, 0.1, 1, 10]
